### ISSUE TITLE
DotMonitoring New logo 

### ISSUE THREAD

**Issue by Arslanshn** [LTMenezes/DotMonitoring#1]
Hi, I want to design a new logo for the project completely free...

**Comment by LTMenezes** [comment]
Hi, Arslanshn!

Thank you for your interest in contributing to this project. You are welcome to suggest a new logo, you can get our current logo [here](https://github.com/LTMenezes/DotMonitoring/blob/master/src/DotMonitoring.Core/WebInterfaceFiles/assets/brand/logo.svg).

You are free to sugest new designs, you can send them here to allow people to look and make suggestions or you can open a Pull Request.

**Comment by Arslanshn** [comment]
https://drive.google.com/open?id=11-IxWeOl28BYC_FR2TdMA48AqGsniuPj
hello I did the logo work I hope you like:)

**Comment by LTMenezes** [comment]
It looks very good, Arslanshn!
Which license are you planning to put it on, Creative Commons? I will also need the source files and the .svg to use it on the dashboard.

Great job!

**Comment by Arslanshn** [comment]
I'm glad you like it. I uploaded it as you like :)
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Lisansı" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Bu eser <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"> Creative Commons Atıf 4.0 Uluslararası Lisansı</a> ile lisanslanmıştır.

**Comment by LTMenezes** [comment]
Very good. Your upload link points to a .png image, could you send me a link with this image as a .svg file?

**Comment by Arslanshn** [comment]
https://drive.google.com/folderview?id=14rTGbT1CE_SZaoYzfSsDeLl8uebZdxC6

**Comment by Arslanshn** [comment]
Hi, Leonardo. The files are just as you want;-)

**Comment by LTMenezes** [comment]
Great, I will merge in the logo as soon as I have some time.

**Comment by LTMenezes** [comment]
Hi Arslanshn! I was checking the .svg files and the DotMonitoring.svg file is perfect but the DotMonitoringReadme.svg file seems to be broken, I can't use it. Could you try fixing it and uploading it again?

**Comment by Arslanshn** [comment]
Hey, I fixed it now.

**Comment by Arslanshn** [comment]
Hi, I can not see the logoy on the readme screen. I fixed the swg file

**Comment by Arslanshn** [comment]
Hi my logo When will you use?

**Comment by LTMenezes** [comment]
Hi @Arslanshn, I will merge it in the upcoming weeks, I don't have time right now.
About the .svg, I saw that you fixed it but the background is not transparent, could you please fix it?

**Comment by Arslanshn** [comment]
Hi, leonardo I can not see the logoy on the readme screen. I fixed the swg file:)

**Comment by LTMenezes** [comment]
Great @Arslanshn, I will take a look and hopefully merge them in this weekend. Thanks for the collaboration.

**Comment by LTMenezes** [comment]
@Arslanshn  I merged it in, you can see it now on our readme. Good job!
